# Generated by Django 5.1 on 2024-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
