# Generated by Django 5.1 on 2024-08-28 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("shipping", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shipping.shipment",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="shipping_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_rates",
                to="shipping.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_rates",
                to="vendors.vendorprofile",
            ),
        ),
    ]
