# Generated by Django 5.1 on 2024-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="applicable_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific products the discount applies to",
                related_name="discounts",
                to="products.product",
            ),
        ),
    ]
